### ISSUE TITLE
rename to staple?

### ISSUE THREAD

**Issue by rurban** [jemc/pony-stable#1]
stable != staple, and stable is a bit misleading. now it's still time, later might be too late

**Comment by jemc** [comment]
- **_stable**_ - not likely to change or fail; firmly established.
- **_stable**_ - a building set apart and adapted for keeping horses.

---
- **_staple**_ - a piece of bent metal or wire pushed through something or clipped over it as a fastening, in particular.
- **_staple**_ - a main or important element of something, especially of a diet.

---

I don't understand why you think **_staple**_ is a better name than **_stable**_, when to me it seems the two definitions of **_stable**_ seem to be more applicable to the project than those of **_staple**_.

**Comment by rurban** [comment]
Oops, so I mixed it up
