### ISSUE TITLE
Non-zero exitcode when there is no bundle.json

### ISSUE THREAD

**Issue by SeanTAllen** [jemc/pony-stable#12]
After the change @dipinhora made to allow for the use of stable with projects that don't define a bundle.json, I switched my emacs flycheck to always use stable if it is installed. This has an interesting effect that when used in a project with no bundle.json that we get an error due to a non-zero exit code.

If not having a bundle.json is ok, should the exit code be 0 instead?

**Comment by jemc** [comment]
@SeanTAllen - with latest `pony-stable` master I _do_ get a zero exit code when running in a directory with no `bundle.json`:

``` bash
$ stable fetch; echo $?
No bundle in current working directory.
0
$ stable env echo foo; echo $?
No bundle in current working directory.
foo
0
```

**Comment by SeanTAllen** [comment]
Odd. Closing until I can come up with something more to reproduce.
