### ISSUE TITLE
pony-stable Arch package seems broken for some CPUs

### ISSUE THREAD

**Issue by superherointj** [jemc/pony-stable#137]
I'm tracking an error that makes pony-stable dump core in certain cases.
To reproduce, just install pony-stable in a machine and run "stable version" would be enough to reproduce it. It'll error as: "Illegal instruction (core dump)"

Errors in: i5-3320M, i5-2520M
Works fine with i7-4510U.

Arch Linux Forum thread:
https://bbs.archlinux.org/viewtopic.php?id=251577

Arch pony-stable package bug report:
https://bugs.archlinux.org/task/64934

Dockerfiles helping triage the problem:
https://gist.github.com/superherointj/fe031e0255d86fc40fc333a7e14de310

It happens in both of these kernels:
    Linux x220-arch 4.19.91-1-lts #1 SMP Sat, 21 Dec 2019 16:34:46 +0000 x86_64 GNU/Linux
    Linux x220-arch 5.4.6-arch1-1 #1 SMP PREEMPT Sat, 21 Dec 2019 16:34:41 +0000 x86_64 GNU/Linux

I'll add more information here as soon as I have more time to do it.

**Comment by superherointj** [comment]
The PKGBUILD maintainer has fixed the problem.

Felix Yan (felixonmars) - Sunday, 22 December 2019, 15:46 GMT-3
The default building target of ponyc seems to be the host CPU. I have added the same arch=x86-64 parameter as the ponyc package in 0.2.2-2. Please try again.

**Comment by SeanTAllen** [comment]
So, you need to pass arch option to make, otherwise it will use the arch of the machine you are building on. See the script we use to build nightly releases, you can use it as an exemplar.

**Comment by superherointj** [comment]
Yes, I think I figured out why I wasn't able to use make in ponyup properly before. Will confirm soon. Is related. When ponyup is ready, I'll close issue there.

Edit: confirmed all is fine now.
