### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by MidAutumnMoon** [jemc/pony-stable#140]
Platform: Manjaro amd64
CPU: Intel i5-2450M (a very old one)

pony-stable was installed (version 0.2.2-2) from community repo.

It can not run :cry:, just says: "[1]   *PID* illegal hardware instruction (core dumped)  *stable*".
That's super weird, I have never seen this when using other pony applications.

I guess this should be the problem of ponyc.

**Comment by MidAutumnMoon** [comment]
I've built pony-stable from-source on master branch, and it can run.

**Comment by SeanTAllen** [comment]
@MidAutumnMoon 

The problem you are encountering would be based on the CPU architecture that the package was built for. The official packages that we release are built for a very generic `x86-64` instruction set. That allows them to run on a wide variety of CPUs. It does, however, come with a performance cost. If you were to build pony-stable and not indicate the architecture, it will build for the specific architecture of the build machine. If then used on an earlier CPU instruction set, you would get the error that you encountered.

I'm not familiar with what the "community repo" is. I assume you are referring to something Manjaro/Arch specific. Perhaps this?

https://www.archlinux.org/packages/community/x86_64/pony-stable/

Is that what you are referring to?

It looks like there was a thread about this here: https://bbs.archlinux.org/viewtopic.php?id=251577

and it appears they fixed it.

At any rate, we don't have control over that packaging nor the architecture they built for.

Your possible options are:

- Report to the maintainer of that AUR package and have them update the `arch=FOO` option to the pony-stable Makefile to be more generic
- Build pony-stable from source
- Use [ponyup](https://github.com/ponylang/ponyup) to install pony-stable
- Download the .tar.gz from our [official releases repository](https://cloudsmith.io/~ponylang/repos/releases/packages/).  Version 0.2.2 is available [here](https://cloudsmith.io/~ponylang/repos/releases/packages/detail/raw/stable-x86-64-unknown-linux.tar.gz/0.2.2/). All .tar.gz packages for x86-64 in the releases repo are built for a very generic x86-64 instruction set. That allows them to run on a wide variety of x86 CPUs but at the cost of some performance.

**Comment by MidAutumnMoon** [comment]
Thanks! And sorry that I've not provided enough information.

I used the build script of pony-stable in the Arch repository on my computer and everything
is fine. So this really should be a bug between hardwares (and maybe of ponyc).

Whatever I've solved the problem and thanks for your replying! :smiley:
