### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by SeanTAllen** [jemc/pony-stable#23]
We should set up Travis and Appveyor to verify that pony-stable builds. From there, we can move to potentially adding tests.

- [ ] Travis
- [x] Appveyor

**Comment by SeanTAllen** [comment]
So, should we test against most recently released Pony version or master? I'm thinking most recently released (and see if we can use our bintray packages on Linux and Windows).

Thoughts?

**Comment by SeanTAllen** [comment]
@kulibali I tried to do an .appveyor.yaml for this and realized I just don't know Windows well enough. Think you can get an .appveyor.yaml together?

**Comment by chalcolith** [comment]
Sure, I can work on this tomorrow.

**Comment by chalcolith** [comment]
AppVeyor is in place and building.  It doesn't deploy to BinTray yet.

**Comment by SeanTAllen** [comment]
Perfect. Thanks.
