### ISSUE TITLE
Make prebuilt pony-stable available

### ISSUE THREAD

**Issue by SeanTAllen** [jemc/pony-stable#26]
Will make it easier for folks to set up their own CI jobs that need stable, if prebuilt stable versions are available.

- [x] available via Bintray for Windows
- [x] available via Bintray for RPM
- [x] available via Bintray for Deb
- [x] available via Homebrew for OSX

Needs #23

**Comment by SeanTAllen** [comment]
@kulibali I'm looking to get this in place so that people have an easier time installing stable. I'm going to take the release process from ponyc and move it over here as applicable. are you game to move do the same for Appveyor?

**Comment by chalcolith** [comment]
Sure, can do.

**Comment by SeanTAllen** [comment]
@kulibali ill let you know when i get started.

**Comment by SeanTAllen** [comment]
I've opened a PR to get pony-stable into homebrew.

https://github.com/Homebrew/homebrew-core/pull/17962

**Comment by SeanTAllen** [comment]
Homebrew PR accepted.

**Comment by chalcolith** [comment]
Once #35 is merged, the AppVeyor build is set up to:

- Grab the latest `ponyc` build from BinTray and use it to compile `pony-stable`.
- Name the resulting file `pony-stable-{version}-{build}.{git-hash}.zip`, where `{version}` comes from the `VERSION` file in the root directory.
- For builds on the `release` branch, deploy to `bintray.com/pony-language/pony-stable-win`.

**Comment by SeanTAllen** [comment]
At this point, this is waiting on a fix to ponylang/changelog-tool and then I can move forward with testing a release.
