### ISSUE TITLE
Some errors are silently eaten and not displayed

### ISSUE THREAD

**Issue by tbillington** [jemc/pony-stable#48]
Running commands using pony stable doesn't seem to do anything on OSX.

I have a bundle.json

```json
{
  "type": "github",
  "repo": "oraoto/pony-websocket"
}
```

When running `stable fetch` nothing happens.

I then tried emptying `bundle.json` then running `stable add github oraoto/pony-websocket`. Nothing happened again, `bundle.json` was still empty.

I then tried `stable add github jemc/pony-inspect` as suggested in the `pony-stable` help command, still no effect.

```
> stable version
0.1.1 [release]
```

**Comment by SeanTAllen** [comment]
@tbillington i assume you have git installed? what version of OSX? I use stable on OSX without issue every day. I'm unable to reproduce.

<img width="696" alt="screenshot 2017-11-04 12 42 26" src="https://user-images.githubusercontent.com/193596/32407321-a7f8f7f0-c15d-11e7-8c60-a4c7a8a39148.png">

**Comment by tbillington** [comment]
OSX 10.12.6

I tried your commands in a fresh directory and it worked :) !

It seems that having a malformed bundle.json in the directory prevented stable from doing anything. As you can see from my terminal history below running add gave no output.

```
~/pwildlife > stable add oraoto/pony-websocket
Couldn't find type 'oraoto/pony-websocket'.
Available types are github, local-git, and local.
~/pwildlife > stable add github oraoto/pony-websocket
~/pwildlife > cat bundle.json
{}
~/pwildlife > ls
bundle.json main.pony   pwildlife
~/pwildlife > stable env ponyc
Building builtin -> /usr/local/Cellar/ponyc/0.20.0/packages/builtin
Building . -> /Users/trent/pwildlife
Error:
websocket: couldn't locate this path
Error:
/Users/trent/pwildlife/main.pony:1:1: can't load package 'websocket'
use "websocket"
^
```

**Comment by SeanTAllen** [comment]
@tbillington do you have a "malformed" bundle.json we can use to test with so we can verify we fixed the issue?

**Comment by tbillington** [comment]
```json
{
  "type": "github",
  "repo": "oraoto/pony-websocket"
}
```
and
```json
{}
```

If the bundle.json is an empty file there is an error message, that's why I thought it was strange when there was no output for the above incorrectly formed bundle.json.

```
> stable add github oraoto/pony-websocket
JSON error at: /Users/trent/pwildlife/bundle.json:1 : Unexpected EOF in top level value
JSON error at: /Users/trent/pwildlife/bundle.json:1 : Unexpected EOF in top level value
JSON error at: /Users/trent/pwildlife/bundle.json:1 : Unexpected EOF in top level value
```
