### ISSUE TITLE
Bundle pony-stable with pony

### ISSUE THREAD

**Issue by jaynagpaul** [jemc/pony-stable#52]
Hello, just out of curiosity. Why isn't pony-stable bundled with the language itself?

**Comment by SeanTAllen** [comment]
pony-stable is a fairly recent addition to the toolchain, lives in its own codebase and what not and can be evolved independently from ponyc. 

when you say bundled do you mean, installed via the same installer?

**Comment by rafaelfess** [comment]
I think I understood what he means.

Maybe what he was thinking is something like the [Rust lang](https://www.rust-lang.org/tools/install) has.

A tool like `rustup` that installs and manages the installation of `cargo` (pony-stable) and `rustc` (ponyc)

**Comment by SeanTAllen** [comment]
Ponyup can now be used to install ponyc and stable. Closing this.
