### ISSUE TITLE
Builds that contain cyclic dependencies cause an infinite loop

### ISSUE THREAD

**Issue by pzel** [jemc/pony-stable#96]
As demonstrated in [this demo app](https://github.com/pzel/ponyc-cyclic-deps-demo), running
`stable env ponyc` in a project that contains cyclic dependencies creates a process that never finishes, consuming more and more memory until it's killed.

#### Current behavior
Cyclic dependencies cause `stable env ponyc` to fall into an infinite loop.

#### Expected behavior
Cyclic dependencies get compiled, as happens when using 'plain' `ponyc`.

#### Software versions where bug appears:
- OS: `Linux tmr.local 4.19.20_1 #1 SMP PREEMPT Thu Feb 7 06:55:19 UTC 2019 x86_64 GNU/Linux`
- Ponyc: `0.25.0-232a0abe [release] compiled with: llvm 3.9.1 -- cc (GCC) 8.2.0 Defaults: pic=true ssl=openssl_0.9.0`
- Stable: `0.1.3-353733f [release]`

**Comment by SeanTAllen** [comment]
@pzel are you interested in working on a fix for this?

**Comment by pzel** [comment]
Yes, I can take a stab.
